server:
  port: 9090
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: 123456ty
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "n6yYy0T9K8l7A2vR4wE1xZ3qM5nB7vC9xZ0mK2jH4gF6dS8aQ1wE3rT5yU7iO9p0"
  refresh-expiration-ms: 604800000